name = "VoiceAdaptation"
uuid = "47c76daa-90d8-4891-8d99-b829cf5b41c6"
authors = ["Cédric BELMANT"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
